spring:
  #数据源设置
  datasource:
    username: icey
    password: Chinano1
    url: jdbc:mysql://localhost:3306/rbac?useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
  #日期格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#mybatis配置信息，使用注解都可以省略
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.lanqiao.rbac.entity
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    cn.cn.lanqiao.rbac.dao: debug