spring:
  #数据源设置
  datasource:
    username: icey
    password: Chinano1
    url: jdbc:mysql://localhost:3306/demo2?useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
  #日期格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #rabbitMQ配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      type: simple
      simple:
        prefetch: 1
        concurrency: 2
        max-concurrency: 2
  mail:
    host: smtp.qq.com
    username: 1919810@qq.com
    password: yuanshenqidong
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
#mybatis配置信息，使用注解都可以省略
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.lanqiao.rbac.entity
  configuration:
    map-underscore-to-camel-case: true
#showSql
logging:
  level:
    cn.lanqiao.rbac.dao: debug
#pagehelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true